export default ({

    GET_FACTUAL_INDUSTRIES_REQUEST:'@Directory/GET_FACTUAL_INDUSTRIES_REQUEST',
    GET_FACTUAL_INDUSTRIES_SUCCESS:'@Directory/GET_FACTUAL_INDUSTRIES_SUCCESS',
    GET_FACTUAL_INDUSTRIES_FAIL:'@Directory/GET_FACTUAL_INDUSTRIES_FAIL',

} as const)