if exists (select * from sys.objects where name='sp_GetCustomerLatestApplicationData' and type='P')
	drop procedure dbo.sp_GetCustomerLatestApplicationData
GO

create procedure dbo.sp_GetCustomerLatestApplicationData(@TAX_ID_NUMBER	char(8))
AS
	select top 1
			a.TAX_ID_NUMBER,
			isnull(a.FIRST_NAME_EN,u.FIRST_NAME_EN) as FIRST_NAME_EN,
			isnull(a.LAST_NAME_EN,u.LAST_NAME_EN) as LAST_NAME_EN,
			isnull(a.SOCIAL_CARD_NUMBER,u.SOCIAL_CARD_NUMBER) as SOCIAL_CARD_NUMBER,
			isnull(a.COMPANY_NAME,u.COMPANY_NAME) as COMPANY_NAME,
			isnull(a.COMPANY_EMAIL,u.COMPANY_EMAIL) as COMPANY_EMAIL,
			rtrim(isnull(a.FACEBOOK,u.FACEBOOK)) as FACEBOOK,
			rtrim(isnull(a.WEBSITE,u.WEBSITE)) as WEBSITE,
			isnull(a.ANNUAL_TURNOVER,u.ANNUAL_TURNOVER) as ANNUAL_TURNOVER,
			isnull(a.IS_CURRENT_ADDRESS_SAME,u.IS_CURRENT_ADDRESS_SAME) as IS_CURRENT_ADDRESS_SAME,
			isnull(a.CURRENT_COUNTRY_CODE,u.CURRENT_COUNTRY_CODE) as CURRENT_COUNTRY_CODE,
			isnull(a.CURRENT_STATE_CODE,u.CURRENT_STATE_CODE) as CURRENT_STATE_CODE,
			isnull(a.CURRENT_CITY_CODE,u.CURRENT_CITY_CODE) as CURRENT_CITY_CODE,
			isnull(a.CURRENT_STREET,u.CURRENT_STREET) as CURRENT_STREET,
			isnull(a.CURRENT_BUILDNUM,u.CURRENT_BUILDNUM) as CURRENT_BUILDNUM,
			isnull(a.CURRENT_APARTMENT,u.CURRENT_APARTMENT) as CURRENT_APARTMENT,
			isnull(a.IS_INDIVIDUAL_ADDRESS_SAME,u.IS_INDIVIDUAL_ADDRESS_SAME) as IS_INDIVIDUAL_ADDRESS_SAME,
			isnull(a.INDIVIDUAL_COUNTRY_CODE,u.INDIVIDUAL_COUNTRY_CODE) as INDIVIDUAL_COUNTRY_CODE,
			isnull(a.INDIVIDUAL_STATE_CODE,u.INDIVIDUAL_STATE_CODE) as INDIVIDUAL_STATE_CODE,
			isnull(a.INDIVIDUAL_CITY_CODE,u.INDIVIDUAL_CITY_CODE) as INDIVIDUAL_CITY_CODE,
			isnull(a.INDIVIDUAL_STREET,u.INDIVIDUAL_STREET) as INDIVIDUAL_STREET,
			isnull(a.INDIVIDUAL_BUILDNUM,u.INDIVIDUAL_BUILDNUM) as INDIVIDUAL_BUILDNUM,
			isnull(a.INDIVIDUAL_APARTMENT,u.INDIVIDUAL_APARTMENT) as INDIVIDUAL_APARTMENT,
			a.ACTIVITY_CODE,
			a.FACTUAL_INDUSTRY_CODE
	from dbo.APPLICATION as a
	left join dbo.[USER] as u
		on a.USER_ID = u.APPLICATION_USER_ID
	where a.TAX_ID_NUMBER = @TAX_ID_NUMBER
	order by a.CREATION_DATE desc
GO
