if exists (select * from sys.objects where name='sp_GetInitialApplicationLoanSpecialist' and type='P')
	drop procedure dbo.sp_GetInitialApplicationLoanSpecialist
GO

create procedure dbo.sp_GetInitialApplicationLoanSpecialist(@APPLICATION_ID		uniqueidentifier,
															@LOAN_SPECIALIST_ID	int)
AS
	select  CREATION_DATE,
		 	ID,
			LOAN_TYPE_ID,
			STATUS_ID,
			MOBILE_PHONE,
			INITIAL_AMOUNT,
			CURRENCY_CODE,
			TAX_ID_NUMBER,
			FIRST_NAME_EN,
			LAST_NAME_EN,
			SOCIAL_CARD_NUMBER,
			COMPANY_NAME,
			COMPANY_EMAIL,
			FACEBOOK,
			WEBSITE,
			ANNUAL_TURNOVER,
			IS_CURRENT_ADDRESS_SAME,
			CURRENT_COUNTRY_CODE,
			CURRENT_STATE_CODE,
			CURRENT_CITY_CODE,
			CURRENT_STREET,
			CURRENT_BUILDNUM,
			CURRENT_APARTMENT,
			IS_INDIVIDUAL_ADDRESS_SAME,
			INDIVIDUAL_COUNTRY_CODE,
			INDIVIDUAL_STATE_CODE,
			INDIVIDUAL_CITY_CODE,
			INDIVIDUAL_STREET,
			INDIVIDUAL_BUILDNUM,
			INDIVIDUAL_APARTMENT,
			ACTIVITY_CODE,
			FACTUAL_INDUSTRY_CODE,
			dbo.f_GetUIRefusalMessage(REFUSAL_REASON) as REFUSAL_REASON,
			dbo.f_GetUIManualMessage(MANUAL_REASON) as MANUAL_REASON,
			dbo.f_GetUIIdentificationMessage(IDENTIFICATION_REASON) as IDENTIFICATION_REASON,
			CLIENT_CODE,
			IS_DATA_COMPLETE,
			ISN
	from dbo.APPLICATION
	where ID = @APPLICATION_ID and LOAN_SPECIALIST_ID = @LOAN_SPECIALIST_ID
GO