create or alter procedure sp_GetLoanSpecialistApplication(@ID	uniqueidentifier)
AS
	select
		a.LS_ENTRY_DATE,
		isnull(a.LS_LOAN_TYPE_ID,'') as LS_LOAN_TYPE_ID,
		isnull(a.LS_CURRENCY_CODE,'') as LS_CURRENCY_CODE,
		isnull(a.LS_LOAN_AMOUNT,0) as LS_LOAN_AMOUNT,
		isnull(a.LS_LOAN_TERM,'') as LS_LOAN_TERM,
		isnull(a.LS_REPAYMENT_DAY,0) as LS_REPAYMENT_DAY,
		isnull(a.BUSINESS_SPACE,0) as BUSINESS_SPACE,
		isnull(a.BUSINESS_STATE_CODE,'') as BUSINESS_STATE_CODE,
		isnull(a.EMPLOYEE_COUNT,0) as EMPLOYEE_COUNT,
		isnull(a.FAMILY_MEMBER_COUNT,0) as FAMILY_MEMBER_COUNT,
		isnull(a.VEHICLE_COUNT,0) as VEHICLE_COUNT,
		isnull(a.IS_AREA_RENTED,0) as IS_AREA_RENTED,
		dbo.ahf_Unicode2ANSI(isnull(a.AREA_RENTED_COMMENT,'')) as AREA_RENTED_COMMENT,
		dbo.ahf_Unicode2ANSI(isnull(a.ACTIVITY_DESCRIPTION,'')) as ACTIVITY_DESCRIPTION,
		p.IS_REAL_ESTATE,
		isnull(p.SHOULD_MAIN_AGREEMENT_SIGNED,0) as SHOULD_MAIN_AGREEMENT_SIGNED,
		isnull(p.IS_MAIN_AGREEMENT_SIGNED,0) as IS_MAIN_AGREEMENT_SIGNED,
		isnull(p.IS_SUCCESSIVE_PLEDGING,0) as IS_SUCCESSIVE_PLEDGING,
		isnull(p.MARKET_PRICE,0) as MARKET_PRICE,
		isnull(p.LIQUID_PRICE,0) as LIQUID_PRICE,
		isnull(p.IS_INSURANCE_CONDITION,0) as IS_INSURANCE_CONDITION,
		isnull(p.IS_INSURANCE_BY_BANK,0) as IS_INSURANCE_BY_BANK,
		isnull(p.INSURANCE_COMPANY_CODE,'') as INSURANCE_COMPANY_CODE,
		isnull(p.APPRAISAL_COMPANY_CODE,'') as APPRAISAL_COMPANY_CODE,
		p.APPRAISAL_DATE,
		isnull(p.OWNERSHIP_CERTIFICATE_NUMBER,'') as OWNERSHIP_CERTIFICATE_NUMBER,
		p.OWNERSHIP_CERTIFICATE_DATE,
		dbo.ahf_Unicode2ANSI(isnull(p.ESTATE_ADDRESS,'')) as ESTATE_ADDRESS,
		isnull(p.ESTATE_RESIDENTIAL_AREA,0) as ESTATE_RESIDENTIAL_AREA,
		isnull(p.ESTATE_LAND_AREA,0) as ESTATE_LAND_AREA,
		isnull(p.VEHICLE_MODEL,'') as VEHICLE_MODEL,
		isnull(p.VEHICLE_VIN,'') as VEHICLE_VIN,
		p.VEHICLE_DATE,
		u.LOGIN
	from APPLICATION a
	join APPLICATION_USER u
		on u.ID=a.LOAN_SPECIALIST_ID
	left join APPLICATION_PLEDGE p
		on a.ID=p.APPLICATION_ID
	where a.ID = @ID
GO
