create or alter procedure sp_GetManualLegalApplication(@ID	uniqueidentifier)
AS
	select
		isnull(INTEREST,0) as INTEREST,
		isnull(LOAN_TERM,LS_LOAN_TERM) as LOAN_TERM,
		isnull(REPAYMENT_DAY,LS_REPAYMENT_DAY) as REPAYMENT_DAY,
		isnull(LOAN_REPAYMENT_FORM_CODE,'') as LOAN_REPAYMENT_FORM_CODE,
		isnull(LOAN_PURPOSE_CODE,'') as LOAN_PURPOSE_CODE,
		isnull(GRACE_PERIOD,0) as GRACE_PERIOD,
		isnull(INVENTORY_BALANCE,0) as INVENTORY_BALANCE,
		isnull(DEBTORS_BALANCE,0) as DEBTORS_BALANCE,
		isnull(CREDITORS_BALANCE,0) as CREDITORS_BALANCE,
		isnull(MONTHLY_EARNING,0) as MONTHLY_EARNING,
		isnull(MONTHLY_COST,0) as MONTHLY_COST,
		isnull(MONTHLY_NET_INCOME,0) as MONTHLY_NET_INCOME,
		isnull(PLEDGE_TYPE_CODE,'') as PLEDGE_TYPE_CODE,
		isnull(APPRAISAL_COMPANY_CODE,'') as APPRAISAL_COMPANY_CODE,
		isnull(BANK_BRANCH_CODE,'') as BANK_BRANCH_CODE
	from APPLICATION
	where ID = @ID
GO
