create or alter procedure sp_GetERegisterClientQueryResult(@TAX_NUMBER varchar(20))
AS
	select ID
		,TAX_NUMBER
		,COUNTRY
		,DISTRICT
		,COMMUNITY
		,STREET
		,BUILDING
		,APARTMENT
		,ADDRESS
		,POSTAL_CODE
		,CERTIFICATE_CODE
		,REGISTRATION_DATE
		,REGISTRATION_CODE
		,TYPE
		,IS_ACTIVE
		,INDUSTRY_CODE
		,NAME_AM
		,NAME_EN
	from EREGISTER_CLIENT_QUERY_RESULT with (NOLOCK)
	where TAX_NUMBER=@TAX_NUMBER
GO
