create or alter procedure sp_GetMainLegalApplication(@ID	uniqueidentifier)
AS
	select
		FINAL_AMOUNT,
		isnull(INTEREST,0) as INTEREST,
		LOAN_TERM,
		REPAYMENT_DAY,
		isnull(LOAN_TEMPLATE_CODE,'') as LOAN_TEMPLATE_CODE,
		isnull(OVERDRAFT_TEMPLATE_CODE,'') as OVERDRAFT_TEMPLATE_CODE,
		IS_REFINANCING,
		isnull(EXISTING_CARD_CODE,'') as EXISTING_CARD_CODE,
		isnull(IS_NEW_CARD,0) as IS_NEW_CARD,
		isnull(CREDIT_CARD_TYPE_CODE,'') as CREDIT_CARD_TYPE_CODE,
		isnull(IS_CARD_DELIVERY,0) as IS_CARD_DELIVERY,
		isnull(dbo.ahf_Unicode2ANSI(CARD_DELIVERY_ADDRESS),'') as CARD_DELIVERY_ADDRESS,
		isnull(BANK_BRANCH_CODE,'') as BANK_BRANCH_CODE,
		isnull(IS_INTERNET_BANK_CHECKED,0) as IS_INTERNET_BANK_CHECKED,
		isnull(IS_ARBITRAGE_CHECKED,0) as IS_ARBITRAGE_CHECKED
	from APPLICATION
	where ID = @ID
GO
