create or alter procedure sp_ProcessEcosystemApplication(
	@APPLICATION_ID				uniqueidentifier,
	@APPLICATION_STATUS_ID		smallint,
	@ECOSYSTEM_APPLICATION_ID	bigint,
	@CLIENT_CODE				char(8)
)
AS
BEGIN
	--Հաստատված
	IF @APPLICATION_STATUS_ID = 24
	BEGIN
		--Confirmed
		UPDATE ECOSYSTEM_APPLICATION
		SET STATUS = 4
			,UPDATED_BY = 'AS'
			,UPDATED_DATE = GETDATE()
		WHERE ID = @ECOSYSTEM_APPLICATION_ID

		--Confirmed
		UPDATE ECOSYSTEM_ADMIN_APPLICATION
		SET STATUS = 7
			,UPDATED_BY = 'AS'
			,UPDATED_DATE = GETDATE()
		WHERE ECOSYSTEM_APPLICATION_ID = @ECOSYSTEM_APPLICATION_ID
	END
	--Մերժված  (9), Մերժված է Բանկի կողմից (17), Ժամկետանց (55)
	ELSE IF @APPLICATION_STATUS_ID IN (9,17,55)
	BEGIN
		--Rejected
		UPDATE ECOSYSTEM_APPLICATION
		SET STATUS = 5
			,UPDATED_BY = 'AS'
			,UPDATED_DATE = GETDATE()
		WHERE ID = @ECOSYSTEM_APPLICATION_ID

		--Rejected
		UPDATE ECOSYSTEM_ADMIN_APPLICATION
		SET STATUS = 6
			,REJECTION_REASON = 11 --Այլ
			,UPDATED_BY = 'AS'
			,UPDATED_DATE = GETDATE()
		WHERE ECOSYSTEM_APPLICATION_ID = @ECOSYSTEM_APPLICATION_ID
	END
END
GO
