create or alter procedure sp_SaveERegisterQueryResult(@APPLICATION_ID	uniqueidentifier,
											 @COUNTRY			char(2),
											 @DISTRICT			nvarchar(20),
											 @COMMUNITY			nvarchar(40),
											 @STREET			nvarchar(100),
											 @BUILDING			nvarchar(40),
											 @APARTMENT			nvarchar(40),
											 @ADDRESS			nvarchar(100),
											 @POSTAL_CODE		varchar(20),
											 @CERTIFICATE_CODE	nvarchar(20),
											 @REGISTRATION_CODE	nvarchar(20),
											 @REGISTRATION_DATE	date,
											 @TYPE				nvarchar(40),
											 @IS_ACTIVE			bit,
											 @INDUSTRY_CODE		varchar(20),
											 @NAME_AM			nvarchar(100),
											 @NAME_EN			varchar(100),
											 @NAME_RU			nvarchar(100),
											 @EXECUTIVES		ERegisterQueryResultExecutive	readonly,
											 @OWNERS			ERegisterQueryResultOwner	readonly)
AS
	BEGIN TRANSACTION
	BEGIN TRY
		declare @CURRENT_STATUS tinyint,@APPLICATION_STATUS_ID smallint

		select @CURRENT_STATUS = STATUS_ID from APPLICATION with (updlock) where ID = @APPLICATION_ID

		if @CURRENT_STATUS <> 2
			RAISERROR (N'Հայտի կարգավիճակն արդեն փոփոխվել է', 17, 1)

		insert into EREGISTER_QUERY_RESULT
			(APPLICATION_ID,COUNTRY,DISTRICT,COMMUNITY,STREET,BUILDING,APARTMENT,ADDRESS,POSTAL_CODE,
			CERTIFICATE_CODE,REGISTRATION_CODE,REGISTRATION_DATE,TYPE,IS_ACTIVE,INDUSTRY_CODE,NAME_AM,NAME_EN,NAME_RU)
		values
			(@APPLICATION_ID,@COUNTRY,@DISTRICT,@COMMUNITY,@STREET,@BUILDING,@APARTMENT,@ADDRESS,@POSTAL_CODE,
			@CERTIFICATE_CODE,@REGISTRATION_CODE,@REGISTRATION_DATE,@TYPE,@IS_ACTIVE,@INDUSTRY_CODE,@NAME_AM,@NAME_EN,@NAME_RU)

		delete from EREGISTER_QUERY_RESULT_EXECUTIVE where APPLICATION_ID=@APPLICATION_ID
		insert into EREGISTER_QUERY_RESULT_EXECUTIVE
			(APPLICATION_ID,COUNTRY,DISTRICT,COMMUNITY,STREET,BUILDING,APARTMENT,ADDRESS,POSTAL_CODE,
			POSITION,PASSPORT_NUMBER,PASSPORT_DATE,PASSPORT_EXPIRY_DATE,PASSPORT_BY,SOCIAL_CARD_NUMBER,
			BIRTH_DATE,GENDER,CITIZENSHIP_CODE,FIRST_NAME,LAST_NAME,PATRONYMIC_NAME,FULL_NAME)
		select @APPLICATION_ID,COUNTRY,DISTRICT,COMMUNITY,STREET,BUILDING,APARTMENT,ADDRESS,POSTAL_CODE,
			POSITION,PASSPORT_NUMBER,PASSPORT_DATE,PASSPORT_EXPIRY_DATE,PASSPORT_BY,SOCIAL_CARD_NUMBER,
			BIRTH_DATE,GENDER,CITIZENSHIP_CODE,FIRST_NAME,LAST_NAME,PATRONYMIC_NAME,FULL_NAME
		from @EXECUTIVES

		delete from EREGISTER_QUERY_RESULT_OWNER where APPLICATION_ID=@APPLICATION_ID
		insert into EREGISTER_QUERY_RESULT_OWNER
			(APPLICATION_ID,COUNTRY,DISTRICT,COMMUNITY,STREET,BUILDING,APARTMENT,ADDRESS,POSTAL_CODE,
			PASSPORT_NUMBER,PASSPORT_DATE,PASSPORT_EXPIRY_DATE,PASSPORT_BY,SOCIAL_CARD_NUMBER,
			BIRTH_DATE,GENDER,CITIZENSHIP_CODE,FIRST_NAME,LAST_NAME,PATRONYMIC_NAME,FULL_NAME,
			IS_FOUNDER,IS_LEGAL,JOIN_DATE,LEAVE_DATE)
		select @APPLICATION_ID,COUNTRY,DISTRICT,COMMUNITY,STREET,BUILDING,APARTMENT,ADDRESS,POSTAL_CODE,
			PASSPORT_NUMBER,PASSPORT_DATE,PASSPORT_EXPIRY_DATE,PASSPORT_BY,SOCIAL_CARD_NUMBER,
			BIRTH_DATE,GENDER,CITIZENSHIP_CODE,FIRST_NAME,LAST_NAME,PATRONYMIC_NAME,FULL_NAME,
			IS_FOUNDER,IS_LEGAL,JOIN_DATE,LEAVE_DATE
		from @OWNERS

		if dbo.f_IsCompanyTypeIE(@TYPE)
			set @APPLICATION_STATUS_ID = 4
		else
			set @APPLICATION_STATUS_ID = 3

		execute sp_ChangeApplicationStatus @APPLICATION_ID,@APPLICATION_STATUS_ID
	END TRY
	BEGIN CATCH
		ROLLBACK TRANSACTION
		declare @ErrorMessage varchar(4000)
		set @ErrorMessage = ERROR_MESSAGE()
		RAISERROR (@ErrorMessage, 17, 1)
		RETURN
	END CATCH
	COMMIT TRANSACTION
GO
