create or alter procedure sp_SaveInitialApplicationFromBank(
	@LOAN_TYPE_ID				char(2),
	@TAX_ID_NUMBER				char(8),
	@COMPANY_NAME				varchar(100)= null,
	@SOCIAL_CARD_NUMBER			char(10),
	@FIRST_NAME_EN				varchar(50)	= null,
	@LAST_NAME_EN				varchar(50)	= null,
	@MOBILE_PHONE				varchar(20) = null,
	@EMAIL						varchar(70) = null,
	@INITIAL_AMOUNT				money,
	@CURRENCY_CODE				char(3),
	@ANNUAL_TURNOVER			money		= null,
	@FACEBOOK					varchar(100)= null,
	@WEBSITE					varchar(100)= null,
	@CURRENT_COUNTRY_CODE		char(2)		= null,
	@CURRENT_STATE_CODE			char(3)		= null,
	@CURRENT_CITY_CODE			char(9)		= null,
	@CURRENT_STREET				varchar(150)= null,
	@CURRENT_BUILDNUM			varchar(30)	= null,
	@CURRENT_APARTMENT			varchar(30)	= null,
	@INDIVIDUAL_COUNTRY_CODE	char(2)		= null,
	@INDIVIDUAL_STATE_CODE		char(3)		= null,
	@INDIVIDUAL_CITY_CODE		char(9)		= null,
	@INDIVIDUAL_STREET			varchar(150)= null,
	@INDIVIDUAL_BUILDNUM		varchar(30)	= null,
	@INDIVIDUAL_APARTMENT		varchar(30)	= null,
	@ACTIVITY_CODE				char(2)		= null,
	@FACTUAL_INDUSTRY_CODE		char(2)		= null,
	@CLIENT_CODE				char(8),
	@ISN						int,
	@IMPORT_ID					int = null
)
AS
	declare @ID uniqueidentifier = newid()
	insert into APPLICATION
		(CREATION_DATE, ID, LOAN_TYPE_ID, TAX_ID_NUMBER, SOCIAL_CARD_NUMBER, FIRST_NAME_EN, LAST_NAME_EN, INITIAL_AMOUNT, CURRENCY_CODE, ISN, CLIENT_CODE, STATUS_ID, SOURCE_ID, ANNUAL_TURNOVER, FACEBOOK, WEBSITE
		, COMPANY_NAME, MOBILE_PHONE, EMAIL
		, CURRENT_COUNTRY_CODE, CURRENT_STATE_CODE, CURRENT_CITY_CODE, CURRENT_STREET, CURRENT_BUILDNUM, CURRENT_APARTMENT
		, INDIVIDUAL_COUNTRY_CODE, INDIVIDUAL_STATE_CODE, INDIVIDUAL_CITY_CODE, INDIVIDUAL_STREET, INDIVIDUAL_BUILDNUM, INDIVIDUAL_APARTMENT
		, ACTIVITY_CODE, FACTUAL_INDUSTRY_CODE, IMPORT_ID)
	values
		(getdate(), @ID, @LOAN_TYPE_ID, @TAX_ID_NUMBER, @SOCIAL_CARD_NUMBER, @FIRST_NAME_EN, @LAST_NAME_EN, @INITIAL_AMOUNT, @CURRENCY_CODE, @ISN, @CLIENT_CODE, 1, 3, @ANNUAL_TURNOVER, @FACEBOOK, @WEBSITE
		, dbo.ahf_ANSI2Unicode(@COMPANY_NAME), @MOBILE_PHONE, @EMAIL
		, @CURRENT_COUNTRY_CODE, @CURRENT_STATE_CODE, @CURRENT_CITY_CODE, dbo.ahf_ANSI2Unicode(@CURRENT_STREET), dbo.ahf_ANSI2Unicode(@CURRENT_BUILDNUM), dbo.ahf_ANSI2Unicode(@CURRENT_APARTMENT)
		, @INDIVIDUAL_COUNTRY_CODE, @INDIVIDUAL_STATE_CODE, @INDIVIDUAL_CITY_CODE, dbo.ahf_ANSI2Unicode(@INDIVIDUAL_STREET), dbo.ahf_ANSI2Unicode(@INDIVIDUAL_BUILDNUM), dbo.ahf_ANSI2Unicode(@INDIVIDUAL_APARTMENT)
		, @ACTIVITY_CODE, @FACTUAL_INDUSTRY_CODE, @IMPORT_ID)
	select @ID
GO
