create or alter procedure sp_SaveERegisterClientQueryResult(@TAX_NUMBER		varchar(20),
											 @COUNTRY			char(2),
											 @DISTRICT			nvarchar(20),
											 @COMMUNITY			nvarchar(40),
											 @STREET			nvarchar(100),
											 @BUILDING			nvarchar(40),
											 @APARTMENT			nvarchar(40),
											 @ADDRESS			nvarchar(100),
											 @POSTAL_CODE		varchar(20),
											 @CERTIFICATE_CODE	nvarchar(20),
											 @REGISTRATION_CODE	nvarchar(20),
											 @REGISTRATION_DATE	date,
											 @TYPE				nvarchar(40),
											 @IS_ACTIVE			bit,
											 @INDUSTRY_CODE		varchar(20),
											 @NAME_AM			nvarchar(100),
											 @NAME_EN			varchar(100),
											 @NAME_RU			nvarchar(100),
											 @EXECUTIVES		ERegisterQueryResultExecutive	readonly,
											 @OWNERS			ERegisterQueryResultOwner	readonly)
AS
	declare @ID uniqueidentifier = newid()

	BEGIN TRANSACTION
	BEGIN TRY
		insert into EREGISTER_CLIENT_QUERY_RESULT
			(ID,TAX_NUMBER,COUNTRY,DISTRICT,COMMUNITY,STREET,BUILDING,APARTMENT,ADDRESS,POSTAL_CODE,
			CERTIFICATE_CODE,REGISTRATION_CODE,REGISTRATION_DATE,TYPE,IS_ACTIVE,INDUSTRY_CODE,NAME_AM,NAME_EN,NAME_RU)
		values
			(@ID,@TAX_NUMBER,@COUNTRY,@DISTRICT,@COMMUNITY,@STREET,@BUILDING,@APARTMENT,@ADDRESS,@POSTAL_CODE,
			@CERTIFICATE_CODE,@REGISTRATION_CODE,@REGISTRATION_DATE,@TYPE,@IS_ACTIVE,@INDUSTRY_CODE,@NAME_AM,@NAME_EN,@NAME_RU)

		delete from EREGISTER_CLIENT_QUERY_RESULT_EXECUTIVE where ID=@ID
		insert into EREGISTER_CLIENT_QUERY_RESULT_EXECUTIVE
			(ID,COUNTRY,DISTRICT,COMMUNITY,STREET,BUILDING,APARTMENT,ADDRESS,POSTAL_CODE,
			POSITION,PASSPORT_NUMBER,PASSPORT_DATE,PASSPORT_EXPIRY_DATE,PASSPORT_BY,SOCIAL_CARD_NUMBER,
			BIRTH_DATE,GENDER,CITIZENSHIP_CODE,FIRST_NAME,LAST_NAME,PATRONYMIC_NAME,FULL_NAME)
		select @ID,COUNTRY,DISTRICT,COMMUNITY,STREET,BUILDING,APARTMENT,ADDRESS,POSTAL_CODE,
			POSITION,PASSPORT_NUMBER,PASSPORT_DATE,PASSPORT_EXPIRY_DATE,PASSPORT_BY,SOCIAL_CARD_NUMBER,
			BIRTH_DATE,GENDER,CITIZENSHIP_CODE,FIRST_NAME,LAST_NAME,PATRONYMIC_NAME,FULL_NAME
		from @EXECUTIVES

		delete from EREGISTER_CLIENT_QUERY_RESULT_OWNER where ID=@ID
		insert into EREGISTER_CLIENT_QUERY_RESULT_OWNER
			(ID,COUNTRY,DISTRICT,COMMUNITY,STREET,BUILDING,APARTMENT,ADDRESS,POSTAL_CODE,
			PASSPORT_NUMBER,PASSPORT_DATE,PASSPORT_EXPIRY_DATE,PASSPORT_BY,SOCIAL_CARD_NUMBER,
			BIRTH_DATE,GENDER,CITIZENSHIP_CODE,FIRST_NAME,LAST_NAME,PATRONYMIC_NAME,FULL_NAME,
			IS_FOUNDER,IS_LEGAL,JOIN_DATE,LEAVE_DATE)
		select @ID,COUNTRY,DISTRICT,COMMUNITY,STREET,BUILDING,APARTMENT,ADDRESS,POSTAL_CODE,
			PASSPORT_NUMBER,PASSPORT_DATE,PASSPORT_EXPIRY_DATE,PASSPORT_BY,SOCIAL_CARD_NUMBER,
			BIRTH_DATE,GENDER,CITIZENSHIP_CODE,FIRST_NAME,LAST_NAME,PATRONYMIC_NAME,FULL_NAME,
			IS_FOUNDER,IS_LEGAL,JOIN_DATE,LEAVE_DATE
		from @OWNERS
	END TRY
	BEGIN CATCH
		ROLLBACK TRANSACTION
		declare @ErrorMessage varchar(4000)
		set @ErrorMessage = ERROR_MESSAGE()
		RAISERROR (@ErrorMessage, 17, 1)
		RETURN
	END CATCH
	COMMIT TRANSACTION
GO