create or alter procedure sp_SaveMLParameter(
	@APPLICATION_ID						uniqueidentifier,
	@AMOUNT_NON_REFINANCING				money,
	@AMOUNT_REFINANCING					money,
	@LOAN_USAGE_CODE					nvarchar(2),
	@AGE								tinyint,
	@UNSECURED_REMAINDER_OTHER_BANKS	money,
	@MONTHLY_REPAYMENT					money,
	@IN_TURN 							money,
	@OUT_TURN							money
)
AS
	BEGIN TRANSACTION
	BEGIN TRY
		delete from ML_PARAMETER where APPLICATION_ID=@APPLICATION_ID
		insert into ML_PARAMETER
			(APPLICATION_ID,AMOUNT_NON_REFINANCING,AMOUNT_REFINANCING,LOAN_USAGE_CODE,AGE,UNSECURED_REMAINDER_OTHER_BANKS,MONTHLY_REPAYMENT,IN_TURN,OUT_TURN)
		values
			(@APPLICATION_ID,@AMOUNT_NON_REFINANCING,@AMOUNT_REFINANCING,@LOAN_USAGE_CODE,@AGE,@UNSECURED_REMAINDER_OTHER_BANKS,@MONTHLY_REPAYMENT,@IN_TURN,@OUT_TURN)
	END TRY
	BEGIN CATCH
		ROLLBACK TRANSACTION
		declare @ErrorMessage varchar(4000)
		set @ErrorMessage = ERROR_MESSAGE()
		RAISERROR (@ErrorMessage, 17, 1)
		RETURN
	END CATCH
	COMMIT TRANSACTION
GO
