create or alter procedure sp_UpdateUserPassword(
	@PROCESS_ID				uniqueidentifier,
	@PHONE					varchar(20),
	@VERIFICATION_CODE_HASH	varchar(1000),
	@PASSWORD_HASH			varchar(1000)
)
AS
	IF EXISTS (
		SELECT *
		FROM USER_PASSWORD_RESET
		WHERE PROCESS_ID = @PROCESS_ID
			AND HASH = @VERIFICATION_CODE_HASH
			AND PHONE = @PHONE
			AND EXPIRES_ON > GETDATE())
		UPDATE APPLICATION_USER
		SET HASH = @PASSWORD_HASH
		WHERE MOBILE_PHONE = @PHONE
	ELSE
	begin
		declare @TRY_COUNT int,@EXPIRES_ON DATETIME,@LIMIT_COUNT int

		SELECT @TRY_COUNT=TRY_COUNT,
			@EXPIRES_ON=EXPIRES_ON
		FROM USER_PASSWORD_RESET
		WHERE PROCESS_ID = @PROCESS_ID
			AND PHONE = @PHONE

		select @LIMIT_COUNT=convert(int,VALUE)
		from SETTING
		where CODE='AUTHORIZATION_CODE_TRY_COUNT'

		if @EXPIRES_ON>GETDATE() and @TRY_COUNT<@LIMIT_COUNT
			update USER_PASSWORD_RESET
			set TRY_COUNT=TRY_COUNT+1
			WHERE PROCESS_ID = @PROCESS_ID
				AND PHONE = @PHONE;

		THROW 51000, N'Օգտագործողի նշանաբանը փոխելու ընթացքում սխալ է առաջացել', 1
	end
GO
