export default ({

    GET_SCORING_RESULTS_REQUEST:'@LoanSettings/GET_SCORING_RESULTS_REQUEST',
    GET_SCORING_RESULTS_SUCCESS:'@LoanSettings/GET_SCORING_RESULTS_SUCCESS',
    GET_SCORING_RESULTS_FAIL:'@LoanSettings/GET_SCORING_RESULTS_FAIL',

    RESET_SCORING_RESULTS:'@LoanSettings/RESET_SCORING_RESULTS',

} as const)