export default ({

    GET_APPRAISAL_COMPANIES_REQUEST:'@Directory/GET_APPRAISAL_COMPANIES_REQUEST',
    GET_APPRAISAL_COMPANIES_SUCCESS:'@Directory/GET_APPRAISAL_COMPANIES_SUCCESS',
    GET_APPRAISAL_COMPANIES_FAIL:'@Directory/GET_APPRAISAL_COMPANIES_FAIL',

} as const)