export default ({

    GET_INDUSTRY_PRODUCTS_REQUEST:'@LoanAppGroupData/GET_INDUSTRY_PRODUCTS_REQUEST',
    GET_INDUSTRY_PRODUCTS_SUCCESS:'@LoanAppGroupData/GET_INDUSTRY_PRODUCTS_SUCCESS',
    GET_INDUSTRY_PRODUCTS_FAIL:'@LoanAppGroupData/GET_INDUSTRY_PRODUCTS_FAIL',

} as const)