export default ({

    GET_LOAN_SPEC_APPLICATION_REQUEST:'@Application/GET_LOAN_SPEC_APPLICATION_REQUEST',
    GET_LOAN_SPEC_APPLICATION_SUCCESS:'@Application/GET_LOAN_SPEC_APPLICATION_SUCCESS',
    GET_LOAN_SPEC_APPLICATION_FAIL:'@Application/GET_LOAN_SPEC_APPLICATION_FAIL',

    SAVE_LOAN_SPEC_APPLICATION_REQUEST:'@Application/SAVE_LOAN_SPEC_APPLICATION_REQUEST',
    SAVE_LOAN_SPEC_APPLICATION_SUCCESS:'@Application/SAVE_LOAN_SPEC_APPLICATION_SUCCESS',
    SAVE_LOAN_SPEC_APPLICATION_FAIL:'@Application/SAVE_LOAN_SPEC_APPLICATION_FAIL',

    RESET_LOAN_SPEC_APPLICATION_DATA:'@Application/RESET_LOAN_SPEC_APPLICATION_DATA',

} as const)