export const ACCESS_TOKEN_NAME: string = 'access_token'
export const BASE_URL: string = 'http://localhost:5006'
//export const BASE_URL: string = 'https://loanspecialist.ameriabank.am'
//export const BASE_URL: string = 'https://smespecialist.ameriabank.am'
export const API_URL: string = '/api/loan'
