export default ({

    GET_APPLICATIONS_REQUEST:'@Applications/GET_APPLICATIONS_REQUEST',
    GET_APPLICATIONS_SUCCESS:'@Applications/GET_APPLICATIONS_SUCCESS',
    GET_APPLICATIONS_FAIL:'@Applications/GET_APPLICATIONS_FAIL',

    RESET_APPLICATIONS_DATA:'@Applications/RESET_APPLICATIONS_DATA',

    SET_APPLICATIONS_PARAMS: '@Applications/SET_APPLICATIONS_PARAMS',

} as const)