export default ({

    GET_GOOD_MONTH_EARNINGS_REQUEST:'@LoanAppGroupData/GET_GOOD_MONTH_EARNINGS_REQUEST',
    GET_GOOD_MONTH_EARNINGS_SUCCESS:'@LoanAppGroupData/GET_GOOD_MONTH_EARNINGS_SUCCESS',
    GET_GOOD_MONTH_EARNINGS_FAIL:'@LoanAppGroupData/GET_GOOD_MONTH_EARNINGS_FAIL',

} as const)