insert into dbo.AGREEMENT_TEMPLATE_BY_TYPE (LOAN_TYPE_ID, CURRENCY_CODE, TEMPLATE_CODE, TEMPLATE_NAME, INTEREST, TERM_FROM, TERM_TO, WAY_ID)
	values ('01', 'EUR', 'TMP1', 'TEMPLATE NAME 1', 7, 6, 6, 1)
GO
insert into dbo.AGREEMENT_TEMPLATE_BY_TYPE (LOAN_TYPE_ID, CURRENCY_CODE, TEMPLATE_CODE, TEMPLATE_NAME, INTEREST, TERM_FROM, TERM_TO, WAY_ID)
	values ('01', 'USD', 'TMP1', 'TEMPLATE NAME 2', 9, 12, 12, 1)
GO
insert into dbo.AGREEMENT_TEMPLATE_BY_TYPE (LOAN_TYPE_ID, CURRENCY_CODE, TEMPLATE_CODE, TEMPLATE_NAME, INTEREST, TERM_FROM, TERM_TO, WAY_ID)
	values ('01', 'AMD', 'TMP3', 'TEMPLATE NAME 3', 12, 24, 24, 1)
GO
insert into dbo.AGREEMENT_TEMPLATE_BY_TYPE (LOAN_TYPE_ID, CURRENCY_CODE, TEMPLATE_CODE, TEMPLATE_NAME, INTEREST, TERM_FROM, TERM_TO, WAY_ID)
	values ('02', 'EUR', 'TMP4', 'TEMPLATE NAME 4', 8, 6, 6, 1)
GO
insert into dbo.AGREEMENT_TEMPLATE_BY_TYPE (LOAN_TYPE_ID, CURRENCY_CODE, TEMPLATE_CODE, TEMPLATE_NAME, INTEREST, TERM_FROM, TERM_TO, WAY_ID)
	values ('02', 'USD', 'TMP5', 'TEMPLATE NAME 5', 10, 18, 18, 1)
GO
insert into dbo.AGREEMENT_TEMPLATE_BY_TYPE (LOAN_TYPE_ID, CURRENCY_CODE, TEMPLATE_CODE, TEMPLATE_NAME, INTEREST, TERM_FROM, TERM_TO, WAY_ID)
	values ('02', 'AMD', 'TMP6', 'TEMPLATE NAME 6', 16, 30, 30, 1)
GO
insert into dbo.AGREEMENT_TEMPLATE_BY_TYPE (LOAN_TYPE_ID, CURRENCY_CODE, TEMPLATE_CODE, TEMPLATE_NAME, INTEREST, TERM_FROM, TERM_TO, WAY_ID)
	values ('03', 'EUR', 'TMP7', 'TEMPLATE NAME 7', 10, 60, 60, 1)
GO
insert into dbo.AGREEMENT_TEMPLATE_BY_TYPE (LOAN_TYPE_ID, CURRENCY_CODE, TEMPLATE_CODE, TEMPLATE_NAME, INTEREST, TERM_FROM, TERM_TO, WAY_ID)
	values ('03', 'USD', 'TMP8', 'TEMPLATE NAME 8', 12, 48, 48, 1)
GO
insert into dbo.AGREEMENT_TEMPLATE_BY_TYPE (LOAN_TYPE_ID, CURRENCY_CODE, TEMPLATE_CODE, TEMPLATE_NAME, INTEREST, TERM_FROM, TERM_TO, WAY_ID)
	values ('03', 'AMD', 'TMP9', 'TEMPLATE NAME 9', 20, 36, 36, 1)
GO
