insert into dbo.APPLICATION_UNSECURED_LIMIT (CURRENCY, AMOUNT)
	values ('AMD',10000000)
GO
insert into dbo.APPLICATION_UNSECURED_LIMIT (CURRENCY, AMOUNT)
	values ('USD',50000)
GO
insert into dbo.APPLICATION_UNSECURED_LIMIT (CURRENCY, AMOUNT)
	values ('EUR', 50000)
GO
