insert into dbo.LOAN_TYPE (CODE, NAME_AM, NAME_EN, DESCRIPTION_AM, DESCRIPTION_EN, REPAYMENT_DAY_FROM, REPAYMENT_DAY_TO, IS_OVERDRAFT, IS_REPAY_DAY_FIXED, IS_CARD_ACCOUNT, IS_REPAY_START_DAY, IS_REPAY_NEXT_MONTH, REPAY_TRANSITION_DAY, IS_CREDIT_LINE, IS_SECURED, IS_ONLINE, IS_AUTO_APPROVED, IS_LOAN_SPECIALIST, IS_CUSTOMER)
	values ('01', N'Ավտոմատ Բիզնես վարկ', 'Automat business loan', N'Ավտոմատ բիզնես վարկերը /մինչև 10 մլն ՀՀ դրամ/ նախատեսված են բիզնեսի զարգացման և ընդլայնման համար։ <a href="https://ameriabank.am/userfiles/file/Loan%20terms/Automatically_SME_ed21_arm.pdf" target="_blank"><b>Իմանալ ավելին:</b></a>', '', 1, 20, 0, 0, 0, 0, 1, 15, 0, 0, 1, 1, 0, 1)
GO
insert into dbo.LOAN_TYPE (CODE, NAME_AM, NAME_EN, DESCRIPTION_AM, DESCRIPTION_EN, REPAYMENT_DAY_FROM, REPAYMENT_DAY_TO, IS_OVERDRAFT, IS_REPAY_DAY_FIXED, IS_CARD_ACCOUNT, IS_REPAY_START_DAY, IS_REPAY_NEXT_MONTH, REPAY_TRANSITION_DAY, IS_CREDIT_LINE, IS_SECURED, IS_ONLINE, IS_AUTO_APPROVED, IS_LOAN_SPECIALIST, IS_CUSTOMER)
	values ('02', N'Ավտոմատ Բիզնես օվերդրաֆտ', 'Automat business overdraft', N'Ավտոմատ բիզնես օվերդրաֆտերը /մինչև 10 մլն ՀՀ դրամ/ բիզնեսի ընթացիկ ծախսերի իրականացման նպատակով ընթացիկ հաշվին կամ Բիզնես քարտի հաշվին տրամադրվող միջոցներ են, որոնց համար վճարվում են ամենամսյա տոկոսներ: Ընթացիկ կատարված մուտքերից գանձվում են հաշվարկված տոկոսները, մյուս մասը մուտքագրվում է քարտին/հաշվին: <a href="https://ameriabank.am/userfiles/file/Loan%20terms/Automatically_SME_ed21_arm.pdf" target="_blank"><b>Իմանալ ավելին:</b></a>', '', 1, 25, 1, 1, 1, 1, 1, 25, 1, 1, 1, 1, 0, 1)
GO
insert into dbo.LOAN_TYPE (CODE, NAME_AM, NAME_EN, DESCRIPTION_AM, DESCRIPTION_EN, REPAYMENT_DAY_FROM, REPAYMENT_DAY_TO, IS_OVERDRAFT, IS_REPAY_DAY_FIXED, IS_CARD_ACCOUNT, IS_REPAY_START_DAY, IS_REPAY_NEXT_MONTH, REPAY_TRANSITION_DAY, IS_CREDIT_LINE, IS_SECURED, IS_ONLINE, IS_AUTO_APPROVED, IS_LOAN_SPECIALIST, IS_CUSTOMER)
	values ('03', N'Երաշխավորությամբ Բիզնես վարկ', 'Unsecured standard loan', N'Երաշխավորությամբ տրամադրվող բիզնես վարկերը նախատեսված են բիզնեսի զարգացման և ընդլայնման համար: Այս վարկատեսակի համար չի պահանջվում գույքի գրավադրում: <a href="https://ameriabank.am/userfiles/file/Loan%20terms/Automatically_SME_ed21_arm.pdf" target="_blank"><b>Իմանալ ավելին:</b></a>', '', 1, 18, 0, 1, 1, 1, 1, 25, 1, 1, 0, 0, 1, 0)
GO
