UPDATE dbo.SETTING SET VALUE='' WHERE CODE='BANK_SERVER_DATABASE'
UPDATE dbo.SETTING SET VALUE='' WHERE CODE='SEND_SERVER_DATABASE'
UPDATE dbo.SETTING SET VALUE='' WHERE CODE='EVENTSTORE_SERVER_DATABASE'
