export default ({

    GET_ACTIVITIES_REQUEST:'@Directory/GET_ACTIVITIES_REQUEST',
    GET_ACTIVITIES_SUCCESS:'@Directory/GET_ACTIVITIES_SUCCESS',
    GET_ACTIVITIES_FAIL:'@Directory/GET_ACTIVITIES_FAIL',

} as const)