export default ({

    GET_CANCELREASONS_REQUEST:'@Directory/GET_CANCELREASONS_REQUEST',
    GET_CANCELREASONS_SUCCESS:'@Directory/GET_CANCELREASONS_SUCCESS',
    GET_CANCELREASONS_FAIL:'@Directory/GET_CANCELREASONS_FAIL',

} as const)