export default ({

    GET_NON_OP_EXPENSES_REQUEST:'@LoanAppGroupData/GET_NON_OP_EXPENSES_REQUEST',
    GET_NON_OP_EXPENSES_SUCCESS:'@LoanAppGroupData/GET_NON_OP_EXPENSES_SUCCESS',
    GET_NON_OP_EXPENSES_FAIL:'@LoanAppGroupData/GET_NON_OP_EXPENSES_FAIL',

} as const)