export default ({

    GET_INSURANCE_COMPANIES_REQUEST:'@Directory/GET_INSURANCE_COMPANIES_REQUEST',
    GET_INSURANCE_COMPANIES_SUCCESS:'@Directory/GET_INSURANCE_COMPANIES_SUCCESS',
    GET_INSURANCE_COMPANIES_FAIL:'@Directory/GET_INSURANCE_COMPANIES_FAIL',

} as const)