export default ({

    GET_PRE_APPROVED_RESULTS_REQUEST:'@Application/GET_PRE_APPROVED_RESULTS_REQUEST',
    GET_PRE_APPROVED_RESULTS_SUCCESS:'@Application/GET_PRE_APPROVED_RESULTS_SUCCESS',
    GET_PRE_APPROVED_RESULTS_FAIL:'@Application/GET_PRE_APPROVED_RESULTS_FAIL',

    SAVE_PRE_APPROVED_RESULTS_REQUEST:'@Application/SAVE_PRE_APPROVED_RESULTS_REQUEST',
    SAVE_PRE_APPROVED_RESULTS_SUCCESS:'@Application/SAVE_PRE_APPROVED_RESULTS_SUCCESS',
    SAVE_PRE_APPROVED_RESULTS_FAIL:'@Application/SAVE_PRE_APPROVED_RESULTS_FAIL',

    RESET_PRE_APPROVED_RESULTS_DATA:'@Application/RESET_PRE_APPROVED_RESULTS_DATA',

} as const)