export default ({

    GET_CURRENCIES_REQUEST:'@Directory/GET_CURRENCIES_REQUEST',
    GET_CURRENCIES_SUCCESS:'@Directory/GET_CURRENCIES_SUCCESS',
    GET_CURRENCIES_FAIL:'@Directory/GET_CURRENCIES_FAIL',

} as const)