export default ({

    GET_APPLICATION_REQUEST:'@Application/GET_APPLICATION_REQUEST',
    GET_APPLICATION_SUCCESS:'@Application/GET_APPLICATION_SUCCESS',
    GET_APPLICATION_FAIL:'@Application/GET_APPLICATION_FAIL',

    GET_LATEST_APPLICATION_SUCCESS:'@Application/GET_LATEST_APPLICATION_SUCCESS',

    SAVE_APPLICATION_REQUEST:'@Application/SAVE_APPLICATION_REQUEST',
    SAVE_APPLICATION_SUCCESS:'@Application/SAVE_APPLICATION_SUCCESS',
    SAVE_APPLICATION_FAIL:'@Application/SAVE_APPLICATION_FAIL',

    RESET_APPLICATION_DATA:'@Application/RESET_APPLICATION_DATA',

} as const)