if exists (select * from sys.objects where name='ACRA_LEGAL_QUERY_RESULT' and type='U')
	drop table ACRA_LEGAL_QUERY_RESULT
GO

CREATE TABLE ACRA_LEGAL_QUERY_RESULT(
	QUERY_DATE				datetime			NOT NULL default getdate(),
	APPLICATION_ID			uniqueidentifier	NOT NULL,
	RESPONSE_XML			nvarchar(max)		NOT NULL,
	PRESENCE_TYPE			varchar(2)			NULL,
	CLASSIFICATION_COUNT	int					NULL,
	REVIEW_DATE				date				NULL,
	LOAN_WORST_CLASS		nvarchar(200)		NULL,
	GUARANTEE_WORST_CLASS	nvarchar(200)		NULL
)
GO

CREATE UNIQUE CLUSTERED INDEX iACRA_LEGAL_QUERY_RESULT1 ON ACRA_LEGAL_QUERY_RESULT (APPLICATION_ID)
GO
