if exists (select * from sys.objects where name='ACRA_QUERY_RESULT_ALL_PAYMENTS' and type='U')
	drop table ACRA_QUERY_RESULT_ALL_PAYMENTS
GO

CREATE TABLE ACRA_QUERY_RESULT_ALL_PAYMENTS(
	APPLICATION_ID	uniqueidentifier	NOT NULL,
	LOAN_ID			varchar(20)			NOT NULL,
	YEAR			smallint			NOT NULL,
	MONTH			tinyint				NOT NULL,
	CUR				char(3)				NOT NULL,
	AMOUNT			money				NOT NULL
)
GO

CREATE CLUSTERED INDEX iACRA_QUERY_RESULT_ALL_PAYMENTS1 ON ACRA_QUERY_RESULT_ALL_PAYMENTS (APPLICATION_ID,LOAN_ID)
GO
