if exists (select * from sys.objects where name='ACRA_QUERY_RESULT_QUERIES' and type='U')
	drop table ACRA_QUERY_RESULT_QUERIES
GO

CREATE TABLE ACRA_QUERY_RESULT_QUERIES(
	APPLICATION_ID	uniqueidentifier	NOT NULL,
	DATE			date				NOT NULL,
	BANK_NAME		nvarchar(100)		NOT NULL,
	REASON			nvarchar(500)		NULL
)
GO

CREATE CLUSTERED INDEX iACRA_QUERY_RESULT_QUERIES1 ON ACRA_QUERY_RESULT_QUERIES (APPLICATION_ID,DATE)
GO
