if exists (select * from sys.objects where name='ACRA_LEGAL_QUERY_RESULT_INTERRELATED' and type='U')
	drop table ACRA_LEGAL_QUERY_RESULT_INTERRELATED
GO

CREATE TABLE ACRA_LEGAL_QUERY_RESULT_INTERRELATED(
	APPLICATION_ID		uniqueidentifier	NOT NULL,
	STATUS				nvarchar(200)		NOT NULL,
	FROM_DATE			date				NOT NULL,
	TO_DATE				date				NOT NULL,
	CUR					char(3)				NOT NULL,
	RISK				nvarchar(200)		NOT NULL,
	CONTRACT_AMOUNT		money				NOT NULL,
	DUE_AMOUNT			money				NOT NULL,
	OVERDUE_AMOUNT		money				NOT NULL,
	OUTSTANDING_PERCENT	money				NOT NULL
)
GO

CREATE CLUSTERED INDEX iACRA_LEGAL_QUERY_RESULT_INTERRELATED1 ON ACRA_LEGAL_QUERY_RESULT_INTERRELATED (APPLICATION_ID)
GO
