if exists (select * from sys.objects where name='ACRA_QUERY_RESULT_LOAN_DUE_DATES' and type='U')
	drop table ACRA_QUERY_RESULT_LOAN_DUE_DATES
GO

CREATE TABLE ACRA_QUERY_RESULT_LOAN_DUE_DATES(
	APPLICATION_ID	uniqueidentifier	NOT NULL,
	LOAN_ID			varchar(20)			NOT NULL,
	YEAR			smallint			NOT NULL,
	MONTH			tinyint				NOT NULL,
	COUNT			int					NOT NULL
)
GO

CREATE CLUSTERED INDEX iACRA_QUERY_RESULT_LOAN_DUE_DATES1 ON ACRA_QUERY_RESULT_LOAN_DUE_DATES (APPLICATION_ID,LOAN_ID)
GO
