if exists (select * from sys.objects where name='ACRA_QUERY_RESULT_PAYMENTS' and type='U')
	drop table ACRA_QUERY_RESULT_PAYMENTS
GO

CREATE TABLE ACRA_QUERY_RESULT_PAYMENTS(
	APPLICATION_ID	uniqueidentifier	NOT NULL,
	YEAR			smallint			NOT NULL,
	MONTH			tinyint				NOT NULL,
	CUR				char(3)				NOT NULL,
	AMOUNT			money				NOT NULL
)
GO

CREATE CLUSTERED INDEX iACRA_QUERY_RESULT_PAYMENTS1 ON ACRA_QUERY_RESULT_PAYMENTS (APPLICATION_ID,YEAR,MONTH)
GO
