if exists (select * from sys.objects where name='AGREEMENT_TEMPLATE_BY_TYPE' and type='U')
	drop table AGREEMENT_TEMPLATE_BY_TYPE
GO

CREATE TABLE AGREEMENT_TEMPLATE_BY_TYPE
(
	LOAN_TYPE_ID	char(2)			NOT NULL,
	CURRENCY_CODE	char(3)			NOT NULL,
	TEMPLATE_CODE	char(4)			NOT NULL,
	TEMPLATE_NAME	nvarchar(50)	NOT NULL,
	INTEREST		money			NOT NULL,
	TERM_FROM		int				NOT NULL,
	TERM_TO			int				NOT NULL,
	WAY_ID			tinyint			NOT NULL
)
GO

CREATE UNIQUE CLUSTERED INDEX iAGREEMENT_TEMPLATE_BY_TYPE1 ON AGREEMENT_TEMPLATE_BY_TYPE(LOAN_TYPE_ID,WAY_ID,CURRENCY_CODE)
GO
