if exists (select * from sys.objects where name='APPLICATION_KYC' and type='U')
	drop table dbo.APPLICATION_KYC
GO

CREATE TABLE dbo.APPLICATION_KYC(
	APPLICATION_ID								uniqueidentifier	NOT NULL,
	CENTER_OF_VITAL_INTERESTS					char(2)				NULL,
	PLACE_OF_BIRTH								char(2)				NULL,
	CITIZENSHIP									char(2)				NULL,
	COUNTRY_OF_RESIDENCE						char(2)				NULL,
	SECOND_CITIZENSHIP							char(2)				NULL,
	RESIDENCE_CERTIFICATE_IN_OTHER_COUNTRY		char(2)				NULL,
	HAVE_YOU_HAD_A_SUBSTANTIAL_US_PRESENCE		bit					NULL,
	ARE_YOU_A_POLITICALLY_EXPOSED_PERSON		bit					NULL,
	ANNUAL_PAID_TAXES							money				NULL,
	EXPECTED_MONTHLY_ACCOUNT_CREDIT_TURNOVER	money				NULL,
	SOURCE_OF_FUNDS_ON_ACCOUNTS					nvarchar(250)		NULL,
	PURPOSE_OF_COOPERATION						nvarchar(250)		NULL
)
GO

CREATE UNIQUE CLUSTERED INDEX iAPPLICATION_KYC1 ON APPLICATION_KYC (APPLICATION_ID)
GO
