if exists (select * from sys.objects where name='APPLICATION_COMPANY_OPERATIONAL_EXPENSE' and type='U')
	drop table dbo.APPLICATION_COMPANY_OPERATIONAL_EXPENSE
GO

CREATE TABLE dbo.APPLICATION_COMPANY_OPERATIONAL_EXPENSE(
	APPLICATION_ID 							uniqueidentifier	NOT NULL,
	COMPANY_OPERATIONAL_EXPENSE_TYPE_CODE	char(2)				NOT NULL,
	AMOUNT									money				NOT NULL,
	COMMENT									nvarchar(100)		NULL
)
GO

CREATE UNIQUE CLUSTERED INDEX iAPPLICATION_COMPANY_OPERATIONAL_EXPENSE1 ON APPLICATION_COMPANY_OPERATIONAL_EXPENSE (APPLICATION_ID,COMPANY_OPERATIONAL_EXPENSE_TYPE_CODE)
GO
