if exists (select * from sys.objects where name='APPLICATION_PLEDGE' and type='U')
	drop table dbo.APPLICATION_PLEDGE
GO

CREATE TABLE dbo.APPLICATION_PLEDGE(
	APPLICATION_ID					uniqueidentifier	NOT NULL,
	IS_REAL_ESTATE					bit					NOT NULL,
	SHOULD_MAIN_AGREEMENT_SIGNED	bit					NOT NULL,
	IS_MAIN_AGREEMENT_SIGNED		bit					NOT NULL,
	IS_SUCCESSIVE_PLEDGING			bit					NOT NULL,
	MARKET_PRICE					money				NULL,
	LIQUID_PRICE					money				NULL,
	IS_INSURANCE_CONDITION			bit					NOT NULL,
	IS_INSURANCE_BY_BANK			bit					NOT NULL,
	INSURANCE_COMPANY_CODE			char(3)				NULL,
	APPRAISAL_COMPANY_CODE			char(3)				NULL,
	APPRAISAL_DATE					date				NULL,
	OWNERSHIP_CERTIFICATE_NUMBER	nvarchar(20)		NULL,
	OWNERSHIP_CERTIFICATE_DATE		date				NULL,
	ESTATE_ADDRESS					nvarchar(100)		NULL,
	ESTATE_RESIDENTIAL_AREA			money				NULL,
	ESTATE_LAND_AREA				money				NULL,
	VEHICLE_MODEL					nvarchar(100)		NULL,
	VEHICLE_VIN						varchar(20)			NULL,
	VEHICLE_DATE					date				NULL
)
GO

CREATE UNIQUE CLUSTERED INDEX iAPPLICATION_PLEDGE1 ON dbo.APPLICATION_PLEDGE(APPLICATION_ID)
GO
