if exists (select * from sys.objects where name='APPLICATION_PREAPPROVED_RESULT' and type='U')
	drop table dbo.APPLICATION_PREAPPROVED_RESULT
GO

CREATE TABLE dbo.APPLICATION_PREAPPROVED_RESULT(
	APPLICATION_ID				uniqueidentifier	NOT NULL,
	ID							tinyint				NOT NULL,
	IS_REFINANCING				bit					NOT NULL,
	APPROVED_AMOUNT				money				NOT NULL,
	INTEREST					money				NOT NULL,
	LOAN_TERM					char(3)				NOT NULL,
	REQUIRED_REAL_ESTATE		money				NOT NULL,
	REQUIRED_MOVABLE_ESTATE		money				NOT NULL,
	MONTHLY_PAYMENT_AMOUNT		money				NOT NULL
)
GO

CREATE UNIQUE CLUSTERED INDEX iAPPLICATION_PREAPPROVED_RESULT1 ON dbo.APPLICATION_PREAPPROVED_RESULT(APPLICATION_ID,ID)
GO
