if exists (select * from sys.objects where name='APPLICATION_COMPANY_BALANCE' and type='U')
	drop table dbo.APPLICATION_COMPANY_BALANCE
GO

CREATE TABLE dbo.APPLICATION_COMPANY_BALANCE(
	APPLICATION_ID 				uniqueidentifier	NOT NULL,
	COMPANY_BALANCE_TYPE_CODE	char(2)				NOT NULL,
	AMOUNT						money				NOT NULL,
	COMMENT						nvarchar(100)		NULL
)
GO

CREATE UNIQUE CLUSTERED INDEX iAPPLICATION_COMPANY_BALANCE1 ON APPLICATION_COMPANY_BALANCE (APPLICATION_ID,COMPANY_BALANCE_TYPE_CODE)
GO
