if exists (select * from sys.objects where name='APPLICATION_GUARANTOR' and type='U')
	drop table dbo.APPLICATION_GUARANTOR
GO

CREATE TABLE dbo.APPLICATION_GUARANTOR (
	ID				int					identity(1,1) NOT NULL,
	APPLICATION_ID	uniqueidentifier	NOT NULL,
	NAME			nvarchar(100)		NOT NULL,
	DOCUMENT_NUMBER	varchar(10)			NOT NULL
)
GO

CREATE UNIQUE CLUSTERED INDEX iAPPLICATION_GUARANTOR1 ON dbo.APPLICATION_GUARANTOR(APPLICATION_ID,ID)
GO
