if exists (select * from sys.objects where name='APPLICATION_OPERATION_LOG' and type='U')
	drop table dbo.APPLICATION_OPERATION_LOG
GO

CREATE TABLE dbo.APPLICATION_OPERATION_LOG (
	ID 					int IDENTITY(1, 1)	NOT NULL,
	DATE				datetime			NOT NULL default getdate(),
	USER_ID				int					NULL,
	LOAN_TYPE_ID		char(2)				NOT NULL,
	OPERATION_CODE		varchar(30)			NOT NULL,
	APPLICATION_ID		uniqueidentifier	NOT NULL,
	OPERATION_DETAILS	nvarchar(max)		NOT NULL,
	IP					varchar(15)			NULL
)
GO

CREATE CLUSTERED INDEX iAPPLICATION_OPERATION_LOG1 ON APPLICATION_OPERATION_LOG (ID)
GO

CREATE INDEX iAPPLICATION_OPERATION_LOG2 ON APPLICATION_OPERATION_LOG (DATE, USER_ID)
GO

CREATE INDEX iAPPLICATION_OPERATION_LOG3 ON APPLICATION_OPERATION_LOG (APPLICATION_ID)
GO
