if exists (select * from sys.objects where name='APPLICATION_KYC_BENEFICIARY' and type='U')
	drop table dbo.APPLICATION_KYC_BENEFICIARY
GO

CREATE TABLE dbo.APPLICATION_KYC_BENEFICIARY(
	ID				int 				IDENTITY(1,1) NOT NULL,
	APPLICATION_ID	uniqueidentifier	NOT NULL,
	NAME			nvarchar(250)		NULL,
	ID_NUMBER		nvarchar(250)		NULL
)
GO

CREATE UNIQUE CLUSTERED INDEX iAPPLICATION_KYC_BENEFICIARY1 ON APPLICATION_KYC_BENEFICIARY (ID)
GO

CREATE INDEX iAPPLICATION_KYC_BENEFICIARY2 ON APPLICATION_KYC_BENEFICIARY (APPLICATION_ID)
GO
