if exists (select * from sys.objects where name='APPLICATION_SCORING_RESULT' and type='U')
	drop table dbo.APPLICATION_SCORING_RESULT
GO

CREATE TABLE dbo.APPLICATION_SCORING_RESULT(
	APPLICATION_ID		uniqueidentifier	NOT NULL,
	APPROVED_AMOUNT_1	money				NULL,
	APPROVED_AMOUNT_2	money				NULL,
	INTEREST			money				NULL,
	REFINANCING_AMOUNT	money				NULL
)
GO

CREATE UNIQUE CLUSTERED INDEX iAPPLICATION_SCORING_RESULT1 ON dbo.APPLICATION_SCORING_RESULT(APPLICATION_ID)
GO
