if exists (select * from sys.objects where name='APPLICATION_PRODUCT' and type='U')
	drop table dbo.APPLICATION_PRODUCT
GO

CREATE TABLE dbo.APPLICATION_PRODUCT(
	ID						int 				IDENTITY(1,1) NOT NULL,
	APPLICATION_ID			uniqueidentifier	NOT NULL,
	PRODUCT_TYPE 			char(1)				NOT NULL,
	CURRENCY				char(3)				NULL,
	CARD_TYPE				nvarchar(100)		NULL,
	INTERNET_BANK_USERNAME	varchar(40)			NULL,
	PROCESSED_CODE			varchar(40)			NULL
)
GO

CREATE UNIQUE CLUSTERED INDEX iAPPLICATION_PRODUCT1 ON APPLICATION_PRODUCT (ID)
GO

CREATE INDEX iAPPLICATION_PRODUCT2 ON APPLICATION_PRODUCT (APPLICATION_ID)
GO
