if exists (select * from sys.objects where name='APPLICATION_COMPANY_OVERHEAD' and type='U')
	drop table dbo.APPLICATION_COMPANY_OVERHEAD
GO

CREATE TABLE dbo.APPLICATION_COMPANY_OVERHEAD(
	ID						int					identity(1,1)	NOT NULL,
	APPLICATION_ID 			uniqueidentifier	NOT NULL,
	INDUSTRY_CODE			char(4)				NOT NULL,
	INDUSTRY_PRODUCT_CODE	char(2)				NOT NULL,
	NET_AMOUNT				money				NOT NULL,
	SALE_AMOUNT				money				NOT NULL,
	PRODUCT_PERCENTAGE		money				NOT NULL
)
GO

CREATE UNIQUE CLUSTERED INDEX iAPPLICATION_COMPANY_OVERHEAD1 ON APPLICATION_COMPANY_OVERHEAD (ID)
GO

CREATE INDEX iAPPLICATION_COMPANY_OVERHEAD2 ON APPLICATION_COMPANY_OVERHEAD (APPLICATION_ID,INDUSTRY_CODE)
GO
