if exists (select * from sys.objects where name='APPLICATION_COMPANY_NONOPERATIONAL_EXPENSE' and type='U')
	drop table dbo.APPLICATION_COMPANY_NONOPERATIONAL_EXPENSE
GO

CREATE TABLE dbo.APPLICATION_COMPANY_NONOPERATIONAL_EXPENSE(
	APPLICATION_ID 								uniqueidentifier	NOT NULL,
	COMPANY_NONOPERATIONAL_EXPENSE_TYPE_CODE	char(2)				NOT NULL,
	AMOUNT										money				NOT NULL,
	COMMENT										nvarchar(100)		NULL
)
GO

CREATE UNIQUE CLUSTERED INDEX iAPPLICATION_COMPANY_NONOPERATIONAL_EXPENSE1 ON APPLICATION_COMPANY_NONOPERATIONAL_EXPENSE (APPLICATION_ID,COMPANY_NONOPERATIONAL_EXPENSE_TYPE_CODE)
GO
