if exists (select * from sys.objects where name='APPLICATION_USER_EMAIL_CONFIRMATION' and type='U')
	drop table [APPLICATION_USER_EMAIL_CONFIRMATION]
GO

CREATE TABLE [dbo].[APPLICATION_USER_EMAIL_CONFIRMATION](
	[APPLICATION_USER] [int] NOT NULL,
	[EMAIL] [varchar](70) NOT NULL,
	[TOKEN] [uniqueidentifier] NOT NULL,
	[IS_ACTIVE] [bit] NOT NULL,
	[CREATION_DATE] [datetime] NOT NULL,
 CONSTRAINT [PK_APPLICATION_USER_EMAIL_CONFIRMATION] PRIMARY KEY CLUSTERED 
(
	[APPLICATION_USER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[APPLICATION_USER_EMAIL_CONFIRMATION] ADD  CONSTRAINT [DF_APPLICATION_USER_EMAIL_CONFIRMATION_CREATION_DATE]  DEFAULT (getdate()) FOR [CREATION_DATE]
GO