if exists (select * from sys.objects where name='APPLICATION_GOOD_MONTH_EARNINGS' and type='U')
	drop table dbo.APPLICATION_GOOD_MONTH_EARNINGS
GO

CREATE TABLE dbo.APPLICATION_GOOD_MONTH_EARNINGS(
	APPLICATION_ID	uniqueidentifier	NOT NULL,
	INDUSTRY_CODE	char(4)				NOT NULL,
	AMOUNT			money				NOT NULL,
	COMMENT			nvarchar(100)		NULL
)
GO

CREATE UNIQUE CLUSTERED INDEX iAPPLICATION_GOOD_MONTH_EARNINGS1 ON APPLICATION_GOOD_MONTH_EARNINGS (APPLICATION_ID,INDUSTRY_CODE)
GO
