if exists (select * from sys.objects where name='APPLICATION_KYC_AFFILIATE' and type='U')
	drop table dbo.APPLICATION_KYC_AFFILIATE
GO

CREATE TABLE dbo.APPLICATION_KYC_AFFILIATE(
	ID				int 				IDENTITY(1,1) NOT NULL,
	APPLICATION_ID	uniqueidentifier	NOT NULL,
	CLIENT_CODE		char(8)				NOT NULL,
	NAME			nvarchar(500)		NULL,
	BIRTH_DATE		date				NULL,
	RELATION		nvarchar(250)		NULL
)
GO

CREATE UNIQUE CLUSTERED INDEX iAPPLICATION_KYC_AFFILIATE1 ON APPLICATION_KYC_AFFILIATE (ID)
GO

CREATE INDEX iAPPLICATION_KYC_AFFILIATE2 ON APPLICATION_KYC_AFFILIATE (APPLICATION_ID)
GO
