if exists (select * from sys.objects where name='APPLICATION_UNSECURED_LIMIT' and type='U')
	drop table dbo.APPLICATION_UNSECURED_LIMIT
GO

CREATE TABLE dbo.APPLICATION_UNSECURED_LIMIT (
	CURRENCY	char(3)	NOT NULL,
	AMOUNT		money	NOT NULL
)
GO

CREATE UNIQUE CLUSTERED INDEX iAPPLICATION_UNSECURED_LIMIT1 ON dbo.APPLICATION_UNSECURED_LIMIT(CURRENCY)
GO
