if exists (select * from sys.objects where name='EREGISTER_INDUSTRY' and type='U')
	drop table EREGISTER_INDUSTRY
GO

CREATE TABLE EREGISTER_INDUSTRY (
	CODE 	varchar(20)		NOT NULL,
	NAME_AM	nvarchar(50)	NOT NULL,
	NAME_EN varchar(50)		NOT NULL
)
GO

CREATE UNIQUE CLUSTERED INDEX iEREGISTER_INDUSTRY1 ON EREGISTER_INDUSTRY(CODE)
GO
