if exists (select * from sys.objects where name='REFINANCING_LOAN' and type='U')
	drop table dbo.REFINANCING_LOAN
GO

CREATE TABLE dbo.REFINANCING_LOAN (
	APPLICATION_ID		uniqueidentifier	NOT NULL,
	ROW_ID 				int					NOT NULL,
	ORIGINAL_BANK_NAME	nvarchar(40)		NOT NULL,
	LOAN_TYPE			nvarchar(40)		NOT NULL,
	INITIAL_INTEREST	money				NOT NULL,
	CURRENCY			char(3)				NOT NULL,
	INITIAL_AMOUNT		money				NOT NULL,
	CURRENT_BALANCE		money				NOT NULL,
	DRAWDOWN_DATE		datetime			NOT NULL,
	MATURITY_DATE		datetime			NOT NULL,
	LOAN_CODE			varchar(16)			NULL
)
GO

CREATE UNIQUE CLUSTERED INDEX iREFINANCING_LOAN1 ON dbo.REFINANCING_LOAN(APPLICATION_ID, ROW_ID)
GO
