if exists (select * from sys.objects where name='RESTRICTED_PASSWORD' and type='U')
	drop table RESTRICTED_PASSWORD
GO

CREATE TABLE RESTRICTED_PASSWORD(
	ID			int			NOT NULL identity(1,1),
	PASSWORD	varchar(50)	NOT NULL
)
GO

CREATE CLUSTERED INDEX iRESTRICTED_PASSWORD1 ON RESTRICTED_PASSWORD(ID)
GO
CREATE UNIQUE INDEX iRESTRICTED_PASSWORD2 ON RESTRICTED_PASSWORD(PASSWORD)
GO
