if exists (select * from sys.objects where name='SCORING_RESULT' and type='U')
	drop table SCORING_RESULT
GO

CREATE TABLE SCORING_RESULT(
	QUERY_DATE		datetime			NOT NULL default getdate(),
	APPLICATION_ID	uniqueidentifier	NOT NULL,
	SCORING_RESULT	money				NOT NULL
)
GO

CREATE UNIQUE CLUSTERED INDEX iSCORING_RESULT1 ON SCORING_RESULT (APPLICATION_ID)
GO
