if exists (select * from sys.objects where name='TAX_QUERY_RESULT_ACTIVITY' and type='U')
	drop table TAX_QUERY_RESULT_ACTIVITY
GO

CREATE TABLE TAX_QUERY_RESULT_ACTIVITY(
	APPLICATION_ID	uniqueidentifier	NOT NULL,
	ACTIVITY_TYPE	nvarchar(200)		NOT NULL,
	PROPORTION		money				NOT NULL
)
GO

CREATE CLUSTERED INDEX iTAX_QUERY_RESULT_ACTIVITY1 ON TAX_QUERY_RESULT_ACTIVITY (APPLICATION_ID)
GO
