if exists (select * from sys.objects where name='TAX_QUERY_RESULT_PROFIT' and type='U')
	drop table TAX_QUERY_RESULT_PROFIT
GO

CREATE TABLE TAX_QUERY_RESULT_PROFIT(
	APPLICATION_ID	uniqueidentifier	NOT NULL,
	PERIOD			varchar(20)			NOT NULL,
	UPDATE_DATE		date				NULL,
	AMOUNT			money				NOT NULL
)
GO

CREATE CLUSTERED INDEX iTAX_QUERY_RESULT_PROFIT1 ON TAX_QUERY_RESULT_PROFIT (APPLICATION_ID)
GO
