if exists (select * from sys.objects where name='TAX_QUERY_RESULT_EMPLOYEE' and type='U')
	drop table TAX_QUERY_RESULT_EMPLOYEE
GO

CREATE TABLE TAX_QUERY_RESULT_EMPLOYEE(
	APPLICATION_ID	uniqueidentifier	NOT NULL,
	NUMBER			int					NOT NULL,
	PERIOD			varchar(20)			NOT NULL,
	UPDATE_DATE		date				NULL
)
GO

CREATE CLUSTERED INDEX iTAX_QUERY_RESULT_EMPLOYEE1 ON TAX_QUERY_RESULT_EMPLOYEE (APPLICATION_ID)
GO
