if exists (select * from sys.objects where name='USER' and type='U')
	drop table [USER]
GO

CREATE TABLE [USER](
	APPLICATION_USER_ID			int				NOT NULL,
	FIRST_NAME_EN				varchar(50)		NULL,
	LAST_NAME_EN				varchar(50)		NULL,
	SOCIAL_CARD_NUMBER			char(10)		NULL,
	COMPANY_NAME				varchar(100)	NOT NULL,
	ANNUAL_TURNOVER				money			NULL,
	TAX_ID_NUMBER				char(8)			NOT NULL,
	COMPANY_EMAIL				varchar(70)		NULL,
	FACEBOOK					nvarchar(150)	NULL,
	WEBSITE						varchar(100)	NULL,
	IS_CURRENT_ADDRESS_SAME		bit				NULL,
	CURRENT_COUNTRY_CODE		char(2)			NULL,
	CURRENT_STATE_CODE			char(3)			NULL,
	CURRENT_CITY_CODE			char(9)			NULL,
	CURRENT_STREET				nvarchar(150)	NULL,
	CURRENT_BUILDNUM			nvarchar(30)	NULL,
	CURRENT_APARTMENT			nvarchar(30)	NULL,
	IS_INDIVIDUAL_ADDRESS_SAME	bit				NULL,
	INDIVIDUAL_COUNTRY_CODE		char(2)			NULL,
	INDIVIDUAL_STATE_CODE		char(3)			NULL,
	INDIVIDUAL_CITY_CODE		char(9)			NULL,
	INDIVIDUAL_STREET			nvarchar(150)	NULL,
	INDIVIDUAL_BUILDNUM			nvarchar(30)	NULL,
	INDIVIDUAL_APARTMENT		nvarchar(30)	NULL,
	ACTIVITY_CODE				char(2)			NULL,
	FACTUAL_INDUSTRY_CODE		char(2)			NULL
)
GO

CREATE UNIQUE CLUSTERED INDEX iUSER1 ON [USER] (APPLICATION_USER_ID)
GO
