export default ({

    GET_INDUSTRY_TYPES_REQUEST:'@LoanAppGroupData/GET_INDUSTRY_TYPES_REQUEST',
    GET_INDUSTRY_TYPES_SUCCESS:'@LoanAppGroupData/GET_INDUSTRY_TYPES_SUCCESS',
    GET_INDUSTRY_TYPES_FAIL:'@LoanAppGroupData/GET_INDUSTRY_TYPES_FAIL',

} as const)