export default ({

    GET_LOAN_PARAMETERS_REQUEST:'@LoanParameters/GET_LOAN_PARAMETERS_REQUEST',
    GET_LOAN_PARAMETERS_SUCCESS:'@LoanParameters/GET_LOAN_PARAMETERS_SUCCESS',
    GET_LOAN_PARAMETERS_FAIL:'@LoanParameters/GET_LOAN_PARAMETERS_FAIL',

} as const)