export default ({

    GET_LOAN_TYPES_REQUEST:'@Directory/GET_LOAN_TYPES_REQUEST',
    GET_LOAN_TYPES_SUCCESS:'@Directory/GET_LOAN_TYPES_SUCCESS',
    GET_LOAN_TYPES_FAIL:'@Directory/GET_LOAN_TYPES_FAIL',

} as const)