export default ({

    GET_BAD_MONTH_EARNINGS_REQUEST:'@LoanAppGroupData/GET_BAD_MONTH_EARNINGS_REQUEST',
    GET_BAD_MONTH_EARNINGS_SUCCESS:'@LoanAppGroupData/GET_BAD_MONTH_EARNINGS_SUCCESS',
    GET_BAD_MONTH_EARNINGS_FAIL:'@LoanAppGroupData/GET_BAD_MONTH_EARNINGS_FAIL',

} as const)