export default ({

    GET_BUSINESS_STATE_TYPES_REQUEST:'@Directory/GET_BUSINESS_STATE_TYPES_REQUEST',
    GET_BUSINESS_STATE_TYPES_SUCCESS:'@Directory/GET_BUSINESS_STATE_TYPES_SUCCESS',
    GET_BUSINESS_STATE_TYPES_FAIL:'@Directory/GET_BUSINESS_STATE_TYPES_FAIL',

} as const)