export default ({

    GET_PLEDGE_TYPES_REQUEST:'@Directory/GET_PLEDGE_TYPES_REQUEST',
    GET_PLEDGE_TYPES_SUCCESS:'@Directory/GET_PLEDGE_TYPES_SUCCESS',
    GET_PLEDGE_TYPES_FAIL:'@Directory/GET_PLEDGE_TYPES_FAIL',

} as const)