export default ({
    USER_LOGIN_REQUEST:'@User/USER_LOGIN_REQUEST',
    USER_LOGIN_SUCCESS:'@User/USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL:'@User/USER_LOGIN_FAIL',

    RESET_USER_LOGIN_FETCH_FAIL:'@User/RESET_USER_LOGIN_FETCH_FAIL',

    USER_INFO_FETCH_REQUEST:'@User/USER_INFO_FETCH_REQUEST',
    USER_INFO_FETCH_SUCCESS:'@User/USER_INFO_FETCH_SUCCESS',
    USER_INFO_FETCH_FAIL:'@User/USER_INFO_FETCH_FAIL',

    USER_LOGOUT:'@User/USER_LOGOUT',
} as const)