export default ({

    GET_LOAN_SETTINGS_REQUEST:'@LoanSettings/GET_LOAN_SETTINGS_REQUEST',
    GET_LOAN_SETTINGS_SUCCESS:'@LoanSettings/GET_LOAN_SETTINGS_SUCCESS',
    GET_LOAN_SETTINGS_FAIL:'@LoanSettings/GET_LOAN_SETTINGS_FAIL',

    GET_LOAN_UNSECUREDLIMITS_SUCCESS: '@LoanSettings/GET_LOAN_UNSECUREDLIMITS_SUCCESS',
    GET_LOAN_FILEMAXSIZE_SUCCESS: '@LoanSettings/GET_LOAN_FILEMAXSIZE_SUCCESS',

    GET_LOAN_SPECIALIST_LOAN_TERMS_SUCCESS: '@LoanSettings/GET_LOAN_SPECIALIST_LOAN_TERMS_SUCCESS',

} as const)