export default ({

    GET_MAIN_APPLICATION_REQUEST:'@Application/GET_MAIN_APPLICATION_REQUEST',
    GET_MAIN_APPLICATION_SUCCESS:'@Application/GET_MAIN_APPLICATION_SUCCESS',
    GET_MAIN_APPLICATION_FAIL:'@Application/GET_MAIN_APPLICATION_FAIL',

    SAVE_MAIN_APPLICATION_REQUEST:'@Application/SAVE_MAIN_APPLICATION_REQUEST',
    SAVE_MAIN_APPLICATION_SUCCESS:'@Application/SAVE_MAIN_APPLICATION_SUCCESS',
    SAVE_MAIN_APPLICATION_FAIL:'@Application/SAVE_MAIN_APPLICATION_FAIL',

    RESET_MAIN_APPLICATION_DATA:'@Application/RESET_MAIN_APPLICATION_DATA',

} as const)