export default ({

    GET_ADDRESS_COUNTRIES_REQUEST:'@Directory/GET_ADDRESS_COUNTRIES_REQUEST',
    GET_ADDRESS_COUNTRIES_SUCCESS:'@Directory/GET_ADDRESS_COUNTRIES_SUCCESS',
    GET_ADDRESS_COUNTRIES_FAIL:'@Directory/GET_ADDRESS_COUNTRIES_FAIL',

    GET_STATES_REQUEST:'@Directory/GET_STATES_REQUEST',
    GET_STATES_SUCCESS:'@Directory/GET_STATES_SUCCESS',
    GET_STATES_FAIL:'@Directory/GET_STATES_FAIL',

    GET_CITIES_REQUEST:'@Directory/GET_CITIES_REQUEST',
    GET_CITIES_SUCCESS:'@Directory/GET_CITIES_SUCCESS',
    GET_CITIES_FAIL:'@Directory/GET_CITIES_FAIL',

} as const)