export default ({

    GET_OTHER_STATISTICS_REQUEST:'@LoanAppGroupData/GET_OTHER_STATISTICS_REQUEST',
    GET_OTHER_STATISTICS_SUCCESS:'@LoanAppGroupData/GET_OTHER_STATISTICS_SUCCESS',
    GET_OTHER_STATISTICS_FAIL:'@LoanAppGroupData/GET_OTHER_STATISTICS_FAIL',

} as const)